name: glass-garden-dev
services:
  glass-garden:
    build:
      context: .
      dockerfile: Dockerfile.dev
    pull_policy: build
    ports:
      - '3000:3000'
    volumes:
      - ./src:/usr/src/app/src
