// Generated by the resource-files plugin in vite.config.ts. Do not edit.
declare module 'virtual:resource-files' {
	import type { FileSystemTree } from '@vivari/core';
	export const instanceGroup: FileSystemTree;
	export const httpLoadBalancer: FileSystemTree;
	export const postgres: FileSystemTree;
}
