// Generated by the webcontainer-snapshots plugin in vite.config.ts. Do not edit.
declare module 'virtual:webcontainer-snapshots' {
	export const instanceGroup: Uint8Array;
	export const loadBalancer: Uint8Array;
}
